# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://m1kc3b.com
baseurl: m1kc3b.com/
title: m1kc3b
author: m1kc3b
description: I'm a Rust developer
avatar: profile.png
email: m1kc3b@gmail.com
github: m1kc3b
# twitter: username
linkedin: m1kc3b
# stackoverflow: username
# medium: username
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
